### ISSUE TITLE
下载69版本提示提取安装包失败

### ISSUE THREAD

**Issue by cznno** [cnjackchen/my-chrome#52]
下载69版本提示提取安装包失败, 是因为不支持新版本安装包吗?

**Comment by cnjackchen** [comment]
应该是网络问题，点击mychrome界面上显示的版本号会显示下载链接，选择其中一个试试。

**Comment by AnyWAT** [comment]
貌似从69开始 chrome://components/ 全部更新错误
![image](https://user-images.githubusercontent.com/37962734/45645423-f9c3a280-baf2-11e8-818e-ba28d9b0efb8.png)

**Comment by cznno** [comment]
> 应该是网络问题，点击mychrome界面上显示的版本号会显示下载链接，选择其中一个试试。

谢谢, 更换了源之后下载正常了
