### ISSUE TITLE
发现一个比较好的特性

### ISSUE THREAD

**Issue by liudonghua123** [cnjackchen/my-chrome#55]
如果把 MyChrome.exe 重命名为 chrome.exe ，则生成的配置文件都是命名为 chrome 的，对于有强迫症的，这个特性比较好，最后再删除 vbs，则看上去更加绿色精简了，赞一个 😄

**Comment by liudonghua123** [comment]
要是可以首次启动可以预转并且配置一些extension，那么打包小一点就好分享给其他人使用了

**Comment by liudonghua123** [comment]
但是还是有一小点问题，`chrome.vbs` 的脚本
```vbs
CreateObject("shell.application").ShellExecute "chrome.exe", "-set"
```
需要改成
```vbs
CreateObject("shell.application").ShellExecute ".\chrome.exe", "-set"
```
否则会启动默认的chrome，并且修改了每次运行了之后又会被重置

**Comment by hjhsjywanan** [comment]
赞一个，么么扎！
